### ISSUE TITLE
Renvois vers les règles

### ISSUE THREAD

**Issue by Tarao84** [octplane/RDTOM-Source#7]
ya un chouille de souci sur les renvois vers les § des règles. Par exemple question http://zoy.org:20080/question/1551 renvoi quand on click dessus vers 7.5.6.1 alors que dans le fichier que jt'avais filé ça renvoyait vers 7.2.7.1 ... :(

**Comment by Tarao84** [comment]
http://zoy.org:20080/question/1284
http://rollerderbytestomatic.com/question/1284
@octplane

**Comment by octplane** [comment]
Alors, y a quand même 602 différences. Je vais joindre un fichier avec  3 colonnes : la question, la règle dans la version FR et celle dans la version EN. Tu peux en checker 4/5 et me confirmer que c'est bien correct dans la version EN ?

[diffs.txt](https://github.com/octplane/RDTOM-Source/files/522945/diffs.txt)

**Comment by Tarao84** [comment]
Yay

**Comment by Tarao84** [comment]
je viens de regarder. globalement EN a raison et FR a tort. il y a malgré tout des exceptions : j'ai regardé 10 questions > EN a raison 7 fois, FR 1 fois et personne 2.

A noter également que pour toutes les questions dont la réponse sur FR est en 7.3 ou .4 ou .5 la réponse EN sera toujours meilleure car dans les règles .3 .4 et .5 n'existent plus ... donc OUI

**Comment by octplane** [comment]
C'est fixé, merci de valider que c'est bon et de closer le bug ensuite... 

http://www.rollerderbytestomatic.fr/question/1551
