### ISSUE TITLE
Format d'affichage du résultat des questions laids comme un cul

### ISSUE THREAD

**Issue by octplane** [octplane/RDTOM-Source#8]
Je parle de ça :

<img width="899" alt="screen shot 2016-10-09 at 19 58 58" src="https://cloud.githubusercontent.com/assets/22177/19222528/e754cdac-8e5a-11e6-9c0e-103ceda8284d.png">

Ou on voit a peine là ou on a cliqué (ouais, c'est là ou c'est écrit perdu) et à peine quelle est la bonne réponse... Je pense que ça peut être mieux...

**Comment by octplane** [comment]
On pourrait sûrement faire un truc plus joli comme ça 

https://dribbble.com/shots/2196973-Take-a-test

**Comment by Tarao84** [comment]
ah oui ça me plait ça !

**Comment by octplane** [comment]
J'ai commencé le travail...

**Comment by Tarao84** [comment]
han c'est joli !

(poussez madame, poussez !)
