### ISSUE TITLE
Reports are broken

### ISSUE THREAD

**Issue by octplane** [octplane/RDTOM-Source#9]
Pas possible de manipuler des reports quand ils ont des accents.

**Comment by octplane** [comment]
Bug avec l'utilisation de myDB à la place de PDO.

Concerne aussi toute les requêtes de database_derbytest.obj

**Comment by Tarao84** [comment]
Si je peux me permettre, ya une légère différence encore entre les 2, même si elle est minime.
Quand tu fais un report sans accent, sur la page http://www.rollerderbytestomatic.fr/admin/#reports, le report apparaît. Si le report possède des accents, il faut cliquer d'abord sur la question pour voir le report.
(mais bon c'est pas top grave)

**Comment by octplane** [comment]
Tu ne te permets rien du tout, tu vas d'abord me soigner cette vilaine peau. Cela dit, merci de me le dire, je jetterai un oeil à l'occasion...

**Comment by Tarao84** [comment]
https://www.youtube.com/watch?v=7Ou5OyNIm78

**Comment by octplane** [comment]
Bon, ben c'est un corollaire de https://github.com/octplane/RDTOM-Source/issues/9#issuecomment-255615252

**Comment by octplane** [comment]
L'interface de cette liste est aussi moche comme un cul. Ca pourrait reprendre le texte de la question et éviter un click à chaque fois. Bref, je fixe le bug, mais l'interface est à refaire à mon avis...

**Comment by Tarao84** [comment]
bah en fait tout est moche comme un cul ...
